name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - new-main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build
        env:
          NODE_ENV: production
          CUSTOM_DOMAIN: 'true'

      - name: Add .nojekyll file
        run: touch out/.nojekyll
        
      - name: Copy CNAME file
        run: cp CNAME out/
        
      - name: Create index.html in root for subfolder navigation
        run: |
          # Create a backup copy of the 404.html in case it's needed
          cp out/404.html out/404.original.html
          # For custom domain, we don't need to copy index.html to 404.html
          # The 404.html should remain as the actual 404 page

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
          cname: exampledesign.co.uk
